import Head from 'next/head';
import Header from '../components/Header';
import Login from '../components/Login';
import { getSession } from 'next-auth/client';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import { db } from '../firebase';
import Widget from '../components/Widget';
export default function Home({ session, posts }) {
	if (!session) return <Login />;
	return (
		<div className='h-screen bg-gray-100 overflow-hidden'>
			<Head>
				<title>Facebook Clone - Next JS</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			{/* Header */}

			<Header />

			<main className='flex '>
				{/* Sidebar */}
				<Sidebar />
				{/* Feed */}
				<Feed posts={posts} />
				{/* Widgets */}
				<Widget />
			</main>
		</div>
	);
}

export async function getServerSideProps(context) {
	//get the user
	const session = await getSession(context);

	const posts = await db.collection('posts').orderBy('timestamp', 'desc').get();

	const docs = posts.docs.map((post) => ({
		id: post.id,
		...post.data(),
		timestamp: null,
	}));

	return {
		props: { session, posts: docs },
	};
}
